---
apiVersion: v1
kind: Namespace
metadata:
  name: gpu-operator
---
apiVersion: v1
data:
  gridd.conf: |
    # Description: Set License Server Address
    # Data type: string
    # Format:  "<address>"
    ServerAddress=192.168.199.246
kind: ConfigMap
metadata:
  name: licensing-config
  namespace: gpu-operator
